import type { PlanDApprovisionnement } from '@shared/core/domain/entities/plan-d-approvisionnement'

// Stands in for the Plan_d_approvisionnement table outside Grist.
export const FAKE_PLANS: readonly PlanDApprovisionnement[] = [
    {
        id: 1,
        nom: 'Plan appro chaufferie Tulle 2024',
        installation: 1,
        typeDePlan: 'création',
        usage: 'énergie',
        natureDonnee: 'prévision',
        statut: 'en fonctionnement',
    },
    {
        id: 2,
        nom: 'Plan appro réseau de chaleur Brive',
        installation: 2,
        typeDePlan: 'projet',
        usage: 'énergie',
        natureDonnee: 'prévision',
        statut: 'projet',
    },
    {
        id: 3,
        nom: 'Plan appro scierie Ussel',
        installation: 3,
        typeDePlan: 'création',
        usage: 'énergie',
        natureDonnee: 'prévision',
        statut: 'projet',
    },
    {
        id: 4,
        nom: 'Plan appro chaufferie Tulle 2025',
        installation: 4,
        typeDePlan: 'projet',
        usage: 'énergie',
        natureDonnee: 'prévision',
        statut: 'projet',
    },
    {
        id: 5,
        nom: 'Plan appro granulés Égletons',
        installation: 5,
        typeDePlan: 'création',
        usage: 'énergie',
        natureDonnee: 'prévision',
        statut: 'en fonctionnement',
    },
    {
        id: 6,
        nom: 'Plan appro cogénération Limoges',
        installation: 6,
        typeDePlan: 'création',
        usage: 'énergie',
        natureDonnee: 'prévision',
        statut: 'obsolète',
    },
    {
        id: 7,
        nom: 'Plan appro chaufferie hôpital Tulle',
        installation: 7,
        typeDePlan: 'projet',
        usage: 'énergie',
        natureDonnee: 'prévision',
        statut: 'en fonctionnement',
    },
    {
        id: 8,
        nom: 'Plan appro RCU Aurillac',
        installation: 8,
        typeDePlan: 'création',
        usage: 'énergie',
        natureDonnee: 'prévision',
        statut: 'projet',
    },
    {
        id: 9,
        nom: 'Plan appro papeterie Saillat',
        installation: 9,
        typeDePlan: 'projet',
        usage: 'énergie',
        natureDonnee: 'prévision',
        statut: 'en fonctionnement',
    },
    {
        id: 10,
        nom: 'Plan appro chaufferie lycée Meymac',
        installation: 10,
        typeDePlan: 'création',
        usage: 'énergie',
        natureDonnee: 'prévision',
        statut: 'abandonné',
    },
    {
        id: 11,
        nom: 'Plan appro réseau Guéret',
        installation: 11,
        typeDePlan: 'projet',
        usage: 'énergie',
        natureDonnee: 'prévision',
        statut: 'projet',
    },
    {
        id: 12,
        nom: 'Plan appro biomasse Clermont',
        installation: 12,
        typeDePlan: 'création',
        usage: 'énergie',
        natureDonnee: 'prévision',
        statut: 'obsolète',
    },
]
